openapi: 3.0.3
info:
  title: Spring AI Enterprise API
  description: API documentation for Spring AI Enterprise application
  version: 1.0.0
  contact:
    name: Spring AI Enterprise Team
    url: https://github.com/yourusername/spring-ai-enterprise
servers:
  - url: http://localhost:8080
    description: Local development server
tags:
  - name: chat
    description: Chat API operations
  - name: documents
    description: Document management operations
paths:
  /api/chat/complete:
    post:
      tags:
        - chat
      summary: Generate a chat response
      description: Generates a response to a user prompt using the AI model
      operationId: chatCompletion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Invalid request
        '500':
          description: Internal server error
  /api/chat/rag:
    post:
      tags:
        - chat
      summary: Generate a RAG-enhanced response
      description: Generates a response using Retrieval-Augmented Generation
      operationId: ragChatCompletion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Invalid request
        '500':
          description: Internal server error
  /api/chat/template/{templateName}:
    post:
      tags:
        - chat
      summary: Generate a response using a specific template
      description: Generates a response using a predefined prompt template
      operationId: templateChatCompletion
      parameters:
        - name: templateName
          in: path
          description: Name of the template to use
          required: true
          schema:
            type: string
            enum: [code, data, summary, qa]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  description: The user's prompt
              required:
                - prompt
              additionalProperties:
                type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Invalid request
        '500':
          description: Internal server error
  /api/chat/tools:
    post:
      tags:
        - chat
      summary: Generate a tool-augmented response
      description: Generates a response using AI model with tool capabilities
      operationId: toolChatCompletion
      parameters:
        - name: toolNames
          in: query
          description: Names of tools to use
          required: false
          schema:
            type: array
            items:
              type: string
              enum: [get_current_weather, analyze_text, analyze_file]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Invalid request
        '500':
          description: Internal server error
  /api/chat/batch:
    post:
      tags:
        - chat
      summary: Process multiple chat requests in batch
      description: Generates responses for multiple prompts in a single request
      operationId: batchChatCompletion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Invalid request
        '500':
          description: Internal server error
  /api/documents:
    get:
      tags:
        - documents
      summary: Get all documents
      description: Retrieves all documents in the system
      operationId: getAllDocuments
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DocumentResponse'
        '500':
          description: Internal server error
    post:
      tags:
        - documents
      summary: Create a new document
      description: Creates a new document in the system
      operationId: createDocument
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentRequest'
      responses:
        '201':
          description: Document created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'
        '400':
          description: Invalid request
        '500':
          description: Internal server error
  /api/documents/{id}:
    get:
      tags:
        - documents
      summary: Get a document by ID
      description: Retrieves a document by its ID
      operationId: getDocument
      parameters:
        - name: id
          in: path
          description: ID of the document to retrieve
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'
        '404':
          description: Document not found
        '500':
          description: Internal server error
    delete:
      tags:
        - documents
      summary: Delete a document
      description: Deletes a document by its ID
      operationId: deleteDocument
      parameters:
        - name: id
          in: path
          description: ID of the document to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Document deleted
        '404':
          description: Document not found
        '500':
          description: Internal server error
  /api/documents/search:
    get:
      tags:
        - documents
      summary: Search for documents by title
      description: Searches for documents with titles containing the search term
      operationId: searchDocuments
      parameters:
        - name: title
          in: query
          description: Search term for document titles
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DocumentResponse'
        '500':
          description: Internal server error
components:
  schemas:
    ChatRequest:
      type: object
      properties:
        prompt:
          type: string
          description: The user's prompt
        systemPrompt:
          type: string
          description: Optional system prompt to guide the AI's behavior
      required:
        - prompt
    ChatResponse:
      type: object
      properties:
        response:
          type: string
          description: The AI-generated response
        timestamp:
          type: string
          format: date-time
          description: The timestamp when the response was generated
    DocumentRequest:
      type: object
      properties:
        title:
          type: string
          description: The document title
        content:
          type: string
          description: The document content
        sourceUrl:
          type: string
          description: The source URL of the document (optional)
        documentType:
          type: string
          description: The type of document (optional)
      required:
        - title
        - content
    DocumentResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: The document ID
        title:
          type: string
          description: The document title
        content:
          type: string
          description: The document content
        sourceUrl:
          type: string
          description: The source URL of the document
        documentType:
          type: string
          description: The type of document
        createdAt:
          type: string
          format: date-time
          description: The creation timestamp
        updatedAt:
          type: string
          format: date-time
          description: The last update timestamp