spring:
  application:
    name: spring-ai-showcase
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_ai_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com
      
server:
  port: 8080

ai:
  openai:
    model: gpt-3.5-turbo
    embedding-model: text-embedding-ada-002
    temperature: 0.7
    max-tokens: 500
  rag:
    top-k: 3
    similarity-threshold: 0.7
    chunk-size: 1000
    chunk-overlap: 200
  vector-db:
    type: pgvector
    dimension: 1536

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method